### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ricardotaborda** [chemMD/Chem_Strip#12]
There is no wiki in the github project.

**Comment by drknnetz** [comment]
I am having trouble using ssh. I am writing code and files in the hpc and previously I was able to push them to our old repository, however since we forked to this new repository my old ssh public key no longer works. If I copy the html files from doxygen manually and paste them into the wiki file it gives us links to each subheader but I cannot push the files directly and this is tedious. Maybe there is a different way for me to do this without using the hpc.
